version: "3"
services:
  #PHP Service
  api-app:
    depends_on:
      - "api-db"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-app
    #restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - api-network

  #Nginx Service
  api-server:
    depends_on:
      - "api-db"
    image: nginx:alpine
    container_name: api-server
    #restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - api-network
  api-db:
    image: postgres:10.2
    container_name: api-db
    tty: true
    ports:
      - 5342:5342
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: laravel
    volumes:
      - apidbdata:/var/lib/postgresql
    networks:
      - api-network

#Docker Networks
networks:
  api-network:
    driver: bridge
#Volumes
volumes:
  apidbdata:
    driver: local
